### ISSUE TITLE
Causing stack trace in TopLevelActivity

### ISSUE THREAD

**Issue by dfreemanRIIS** [dfreemanRIIS/Starbuzz#5]
E/Database: close() was never explicitly called on database '/data/user/0/com.example.dfreeman.starbuzz/databases/starbuzz' 
            net.sqlcipher.database.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here
                at net.sqlcipher.database.SQLiteDatabase.<init>(SQLiteDatabase.java:2343)
                at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1115)
                at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1179)
                at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:162)
                at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:227)
                at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:214)
                at com.example.dfreeman.starbuzz.TopLevelActivity.onCreate(TopLevelActivity.java:52)
                at android.app.Activity.performCreate(Activity.java:6237)
                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                at android.app.ActivityThread.-wrap11(ActivityThread.java)
                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                at android.os.Handler.dispatchMessage(Handler.java:102)
                at android.os.Looper.loop(Looper.java:148)
                at android.app.ActivityThread.main(ActivityThread.java:5417)
                at java.lang.reflect.Method.invoke(Native Method)
                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
E/EGL_emulation: tid 2629: eglSurfaceAttrib(1165): error 0x3009 (EGL_BAD_MATCH)

**Comment by dfreemanRIIS** [comment]
Occurs specifically when favorite is unchecked

**Comment by dfreemanRIIS** [comment]
Fixed in commit 5eba2bdd79915e6df251d6485ac406f7fd695e03
